
project_id = "rppiggskrhysmrlbkfhe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[realtime]
enabled = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhooks]
verify_jwt = false

[functions.create-stripe-customer]
verify_jwt = true

[functions.sync-stripe-customers]
verify_jwt = true

[functions.sync-stripe-subscriptions]
verify_jwt = true

[functions.scrape-indices]
verify_jwt = true

[functions.scrape-stocks]
verify_jwt = true
