// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rppiggskrhysmrlbkfhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcGlnZ3Nrcmh5c21ybGJrZmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzQ3NDYsImV4cCI6MjA2MjA1MDc0Nn0.m3DIMXRUHsbSTTsrDwRa9FJi7cHv1Ep1OdaMn6rzfc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);